### PR TITLE
Experiment with safe methods on records

### PR DESCRIPTION
**Pull request by jeddeloh**
So I think I was thinking about this all wrong. It's only unsafe to write _bindings_ to an object method when using records. So we need to use `bs.send` for the `Js_` bindings, but after that we have no such limitations. Here, the function on the reason record has a closure to the original `Js_` object and the method is called using a `bs.send` binding. With this pattern, I think we can move to a much better api where you can destructure methods like `fetchMore` directly on the query result, etc.

In the changes, you can see the unsubscribe method that used to fail when the Js bindings were written directly as a record, but this works perfectly fine.

### CODE REVIEW

**Comment by jeddeloh** [comment]
I took this a bit further to see what the entire `QueryResult` would like like. I like it. It's definitely noisier to write, but I think the ergonomics are worth the payoff. Notice that there's no longer a need to pass the parse/serialize functions along on the result to be used in the method functions because they're all available in the closure from when the result was created.

**Comment by jfrolich** [comment]
Yep amazing. This is going to make our PR a lot smaller, and with no downsides, I think this API is a lot more ergonomic (and closer to the JS one.

**Comment by idkjs** [comment]
Wow. This is too funny. I was just about to write you about this. I dont know if this affects `refetch` yet. Seems like current version `refetch` does not do what we think it does. In the apollo [docs](https://www.apollographql.com/docs/react/data/queries/), there is this example ->https://codesandbox.io/s/queries-example-app-final-nrlnl. I reproduced it in reason, https://github.com/idkjs/apollo-docs-in-reason-queries-example and noticed that in order for `QueryResult.refetch` to work, you must pass in the variables unlike in the `js` version. Is this expected or am I missing something. Relevent code is:
https://github.com/idkjs/apollo-docs-in-reason-queries-example/blob/857efee17e3442155b413c63e454ae14947332af/src/App.re#L50-L58
```ocaml
          onClick={_ =>
            queryResult->QueryResult.refetch(
              // you have to pass the variables back in or wont do anything
              GetDogPhoto.serializeVariables(variables),
            )
            |> ignore
          }>
          "Refetch!"->React.string
        </button>
```

If you dont pass the variables back in, it will not refetch.

**Comment by jeddeloh** [comment]
@idkjs, in general, variables are always required in this library (passing no variables is represented as passing `unit`) because it's the only way to make it truly safe. I suspect the compiler would actually be telling you this, but the issue is being swallowed by `ignore`? Fwiw, I recommend never using `ignore` and write an `Ignore.re` file that has functions for ignoring specific types. `external ignorePromise = Js.Promise.t('a) => unit = "%identity"`. This would catch situations where you have forgotten to fully apply the function, etc.

**Comment by jeddeloh** [comment]
Ok, I think I've completed moving all the `bs.send` methods to live on the records directly that I want to. It ended up being a lot more complicated than I thought because a lot of these things get passed around and used internally by Apollo Client so it's important to preserve the js interface alongside the reason one. I'll probably merge this tomorrow.

**Comment by jfrolich** [comment]
But if you do `result.refetch()` wouldn't that just refetch the query with the variables that are passed into the `Query.use` function? Why wouldn't that be safe?

**Comment by jeddeloh** [comment]
> But if you do result.refetch() wouldn't that just refetch the query with the variables that are passed into the Query.use function? Why wouldn't that be safe?

It would be, and I think this function needs to be updated. Sorry, I wasn't really clear since the first thing I was trying to do was address the comment "Seems like current version refetch does not do what we think it does" was actually a problem of the function not getting fully applied (and I knew since variables are generally required across the library). Then I lost track of the issue with all the rest of the changes and PMs. 😅

**Comment by jeddeloh** [comment]
Made variables optional on refetch. Merging.

**Pull request merged**
