### PR TITLE
Reason variables

### PR DESCRIPTION
**Pull request by jeddeloh**
This is a companion PR for https://github.com/reasonml-community/graphql-ppx/pull/175.

That PR makes it possible for hooks and client methods now accept `t_variables` instead of `Raw.t_variables`. The advantage of this is that records can be the primary way of passing variables and `makeVariables` is a convenience function for when you want to only pass a few optional variables. Using `Raw. t_variables` before allowed you to explicitly pass null arguments, however. To accommodate this, you can now pass a `mapNullVariables` (name?) function to anything that takes `t_variables`. Something like this:
```
  let queryResult = ExampleQuery.use(
    ~mapNullVariables=(jsVars => {
      ...jsVars,
      explicitNullableArg: Js.Nullable.null
    }),
    {id: "1": explicitNullableArg: None}
  );
```

I'm only really concerned with being able to pass `t_variables` at the call site, so everywhere else things are typed as `Raw.t_variables`. I think that's fine and perhaps even preferable in some cases.

### CODE REVIEW

**Comment by jfrolich** [comment]
Ah that's nifty!

**Comment by jfrolich** [comment]
Wanna pull the trigger on this?

**Comment by jeddeloh** [comment]
>Ah that's nifty! Maybe just mapRawVariables?

That feels more accurate. What about `mapJsVariables`? I've avoided raw in favor of Js in the types :shrug:

**Comment by jeddeloh** [comment]
> Wanna pull the trigger on this?
Let's do it!

**Comment by jfrolich** [comment]
> That feels more accurate. What about `mapJsVariables`? I've avoided raw in favor of Js in the types 🤷

Yes, sure

**Pull request merged**
